title: Smooks
theme: minima
baseurl: /smooks.github.io
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=rouge
    - stylesdir=assets/css