---
redirect_from:
  - /v2/faq/
---

:page-liquid:

= Frequently Asked Questions
:sectnums:
:showtitle:
:toc:
:toc-title:

+++
<span data-page-nav="{{ '/faq' | prepend: site.baseurl }}"></span>
+++

==== What is the easiest way to get started with Smooks?

A practical way to getting started with Smooks is to:

. Read the link:documentation/#fundamentals[Smooks fundamentals] section.
. Download and run some of the https://github.com/smooks/smooks-examples/tree/v6[examples].

==== How do I use Smooks from a project managed with https://maven.apache.org/[Maven]?

Visit the link:maven[Maven page].

==== What is the Smooks processing model?

The Smooks processing model is designed around the concepts of readers, events, chunks/fragments, selectors, and visitors. Smooks fires a hierarchy of *events* from a structured data source (e.g., JSON) thanks to a *reader*. An event is the smallest unit of data that a Smooks application can target for data integration. User-defined and built-in visitors use XPath-like *selectors* to target emitted events or *chunks* of these emitted events. A *visitor* is a unit of behaviour that processes a targeted event or chunk of events (i.e., fragment) to execute a data integration task such as transformation, routing, enrichment, binding, filtering, and so on.

==== What is the configuration model of Smooks?

Resource configs define resources driving the behaviour of Smooks. These resources could be readers, visitors, system resources, or even ad-hoc resources. A resource config is primarily composed of a selector, a type, the resource itself, and a key/value set of parameters. Resource configs can be declared from the Java or XML API of Smooks.

==== What is a fragment/chunk?

A chunk, also known as a fragment, is a hierarchy of events emitted from a source. Specifically, it is a (1) start event, (2) followed by zero or more child events, and (3) terminated by an end event. The application defines the chunk's boundaries but, practically speaking, a chunk could correspond to a CSV record, an XML element, a JSON field, an EDI segment, etc...

==== What is a selector?

At a fundamental level, a Smooks applications is composed of a sequence of resource configs, typically declared in an XML file. Smooks activates a resource at runtime through its resources config `selector` attribute. With some exceptions, the selector is an XPath-like expression that points to one or more events in the stream. When Smooks fires an event (e.g., an end event), if the resource config selector matches the event, Smooks applies the corresponding resource to the event or fragment which results in an operation such as transformation, filtering, routing, binding, etc...

==== Is Smooks an alternative to XML transformation technologies such as XSLT?

While Smooks does indeed borrow a number of concepts from XSLT, and XML more generally, it should not be conflated with XSLT or other transformation solutions. XSLT is an XML language that uses pattern-matching for transforming XML documents into other XML documents. Smooks is a _framework_ for link:documentation#fragment_based_processing[_event-driven_, _fragment-based_ data integration] using XML (e.g., XSLT, DFDL, etc...) and _non-XML_ (e.g., Java, https://groovy-lang.org/[Groovy], https://freemarker.apache.org/[FreeMarker], Docker, etc...) solutions. Smooks empowers you to apply multiple independent XSLT resources on an event stream alongside other resources in the context of a single execution.

==== How does Smooks compare with enterprise application integration (EAI) frameworks like Camel or Mule?

https://camel.apache.org/[Camel] and https://github.com/mulesoft/mule[Mule] are frameworks for building message-oriented middleware. The unit of data within these frameworks is a message: a packet consisting of a payload and metadata. While this data abstraction is certainly useful in many integration scenarios, it can lead to accidental complexity when the data needs to be broken down and processed efficiently. Depending on the context, a https://www.enterpriseintegrationpatterns.com/patterns/messaging/Sequencer.html[splitter] can help reduce the complexity. On the other hand, Smooks is arguably a better candidate since it is geared towards this problem domain. Therefore, we generally recommend leveraging an EAI framework for connectivity and lightweight data processing whereas let Smooks do the heavy lifting in data integration.

==== Can I pre-process individual chunks of a stream and then apply a transformation to the overall stream?

This is a classic Smooks usecase. See the https://github.com/smooks/smooks-examples/tree/v6/xslt-groovy[xslt-groovy example]. It uses `core:smooks` (i.e., pipeline) construct together with the `core:rewrite` construct to pre-process a date event in order for the date to be more consumable by XSLT. The XSLT script is then applied to the event stream with the `#document` (i.e., root) selector. This removes any need to have convoluted date processing logic within the XSLT script.

==== Can Smooks ingest non-XML formats?

Certainly. You can leverage one the many out-of-the-box readers, or develop your own Smooks reader, to ingest a non-XML source (based on a profile if necessary). The reader emits events from the source, allowing the downstream Smooks resources to target and process the data. See the https://github.com/smooks/smooks-examples/tree/v6/edi-to-xml[edi-to-xml] and https://github.com/smooks/smooks-examples/tree/v6/csv-to-xml[csv-to-xml] tutorials.

==== What is the difference between the link:documentation#java_binding[JavaBean cartridge] and XML data binding frameworks like JAXB, Apache XMLBeans, and XStream?

The JavaBean cartridge is not designed to be an alternative to existing XML data binders such as those listed above. A dedicated XML data binding solution should be considered if the only requirement is that of marshalling Java objects into XML and unmarshalling XML into objects.

The JavaBean cartridge is a useful alternative:

. For binding non-XML data.
. For binding XML data that does not line up with the target Java object model.
. In situations where your source data model does not conform to any schema. Some tools (e.g., JAXB and XMLBeans) require you to have an XSD, from which the Java model is generated and against which the source message is validated.
. Performing link:documentation#java_binding_configuration_details[Expression Based Bindings].
. For creating link:documentation#java_binding_configuration_details[Virtual Object Models]. This can be very useful when performing model driven transformations.
. For binding XML data where the XML model's dataset is a superset of the Java model's dataset i.e. where you need to selectively pick data from the source XML.
. In support of complex splitting, transformation, and routing (as well as other operations).

The preceding list is not exhaustive. There are other use cases where Java binding with Smooks makes sense. However, the rule of thumb is that if all you are interested in is straightforward marshalling and unmarshalling between Java and XML, then an XML data binder is likely a more practical solution. That is, as long as your use case fits inside the parameters set down by these frameworks. If your use case cannot be solved using an XML data binder without major headaches, then Smooks could be the solution for you!

==== How do I configure a Java resource?

Check out the https://github.com/smooks/smooks-examples/tree/v6/java-basic[java-basic] example.

==== How do I configure an XSLT resource?

. Check out the link:documentation#xslt_templating[user guide].
. Check out the https://github.com/smooks/smooks-examples/tree/v6[examples].

==== How do I configure a FreeMarker resource?

. Check out the link:documentation/#freemarker_templating[user guide].
. Check out the templating https://github.com/smooks/smooks-examples/tree/v6[examples].

==== How do I configure a StringTemplate resource?

. Check out the link:/javadoc/v1.7.1/smooks/org/milyn/templating/stringtemplate/StringTemplateContentHandlerFactory[StringTemplateContentHandlerFactory Javadocs].
. Check out the templating https://github.com/smooks/smooks-examples/tree/v6[examples].

==== How do I configure a Groovy resource?

. Check out the link:documentation/#groovy[user guide].
. Check out the https://github.com/smooks/smooks-examples/tree/v6[examples].

==== How do I target the root event of a stream without specifing the name of the root event?

Set the resource config selector to `#document`.

==== How do I target all events of a stream?

Set the resource config selector to `*`.

==== What happens to events that I do not target?

Un-targeted events are directed to the final output. This is unlike most templating solutions (e.g., XSLT) where this would result in these fragments being omitted from the result.

==== Can I target a fragment with multiple resources?

You can. They will be sorted an applied by Smooks in order of their configuration specificity. See the link:/javadoc/v1.7.1/smooks/org/milyn/cdr/SmooksResourceConfigurationSortComparator[SmooksResourceConfigurationSortComparator].

==== What are the technologies that Smooks supports?

Smooks does not limit you to any single technology. You can write your own extensions but Smooks comes with its own extensions that are bundled together to form _cartridges_. A cartridge adds one or more resources to Smooks to support a particular technology.

==== Apart from transformation, what other forms of processing are possible with Smooks?

The core of Smooks has no notion of data transformation. Smooks is an engine for applying visitors to events emitted from a data source. A visitor could be a transformer, or it could implement logic for processing or analysing data in any way to fit your use case. In other words, the answer to this question is "whatever type of processing you require". You only need to implement a visitor and hook it up with Smooks from a resource config. You can have multiple visitors interact with each other via the link:/javadoc/v2.0.0/smooks/org/smooks/api/ExecutionContext[execution context]

==== Can a single Smooks instance have multiple concurrent executions?

Absolutely! Smooks is thread-safe.

==== Can Smooks be extended to support other libraries, frameworks, and platforms?

Yes. To add support for another transformation or processing technology, you need to implement a link:/javadoc/v2.0.0/smooks/org/smooks/api/delivery/ContentHandlerFactory.html[`org.smooks.api.delivery.ContentHandlerFactory`] for the provider. As examples, see the following `ContentHandlerFactory` implementations:

. link:/javadoc/v1.7.1/smooks/org/milyn/templating/xslt/XslContentHandlerFactory[XslContentHandlerFactory]: Adds support for XSLT.
. link:/javadoc/v1.7.1/smooks/org/milyn/templating/stringtemplate/StringTemplateContentHandlerFactory[StringTemplateContentHandlerFactory]: Adds support for the https://www.stringtemplate.org/[StringTemplate] templating framework.
. link:/javadoc/v1.7.1/smooks/org/milyn/smooks/scripting/groovy/GroovyContentHandlerFactory[GroovyContentHandlerFactory]: Adds support for https://groovy-lang.org/[Groovy] scripted resource.

Registering the `ContentHandlerFactory` is a matter of adding a configuration file named `org.smooks.api.delivery.ContentHandlerFactory` to the `META-INF/services` directory and declaring the `ContentHandlerFactory` implementation class(es).
