---
layout: post
title: "Smooks v1.3… Available for download"
date: 2010-6-28
author:  Tom Fennelly
tags: ["EDI"]
---

Bård (Langöy) and I have been doing lots of work on improving our EDI support, specifically in the area of handling http://www.unece.org/trade/untdid/welcome.htm[UN/EDIFACT] (http://en.wikipedia.org/wiki/UN/EDIFACT[WikipediA]) message http://www.unece.org/trade/edifact/untdid/d300_s.htm#i[Interchanges].  The following improvements are now in the Smooks v1.4 codebase (available from the 1.4-SNAPSHOT):

1. *A new* http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#UN.2FEDIFACT[*UN/EDIFACT Interchange Reader*] (_<unedifact:reader>_), which allows Smooks to process UN/EFIFACT message Interchanges (one or more UN/EDIFACT messages wrapped in the UN/EDIFACT Interchange control segments).
2. A new *Maven/Ant* tool called the "*EDI Conversion Tool*" (*ECT*) that can take the http://www.unece.org/trade/untdid/down_index.htm[official UN/EDIFACT message definition directory zip files] and from them, generate a jar file containing a http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[set of equivalent Smooks EDI Mapping Models].  This tool is very easy to configure and use, but we are in the processing of pre-generating a library of these jars for all the UN/EDIFACT message sets and making them available trough the central maven repository, making it even easier to consume UN/EDIFACT messages with Smooks.  We hope to add support for other formats (X.12, HL7 etc) in future releases of Smooks.

So that’s what’s available in the current 1.4 codebase (1.4-SNAPSHOT), but we’re also in the process of making more additions to this for Smooks v1.4.  We’re extending the *EDI Java Compiler* (*EJC*) tools to support Java Model generation from the http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model sets] generated by the ECT tool (mentioned above).  We’ll also make these available as pre-built jar files from the Maven repository.

Another improvement we’ve made in the 1.4 codebase is the addition of support for *Java Model to EDI serialization* on the EJC generated Java object models, meaning we’ll be able to do full round trip binding of an EDI (and UN/EDIFACT) message to a populated Java Object model that can be modified and then serialize back out to an EDI stream.  Or, your app can "manually" construct the same Java Object models and serialize them out to an EDI Stream (think JAXB).
Generating a Mapping Model Set using ECT

== Generating a Mapping Model Set using ECT

The easiest way to consume UN/EDIFACT messages using Smooks is to use ECT (EDI Conversion Tool) to generate the http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] (if we haven’t already pre-built them).  The steps are really easy:

1. Download the official UN/EDIFACT message definitions directory zip file you are interested in http://www.unece.org/trade/untdid/down_index.htm[from the UNECE website].
2. Create a maven module for the http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] to be generated and add the maven-ect-plugin (see below) to it’s POM.
3. Execute "_mvn clean install_" in your maven module and the http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] jar file will be generated as normal in the modules target folder, and installed into your local maven repository.

The following is an example of the maven module POM for generating the http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model] set jar for the http://www.unece.org/trade/untdid/down_index.htm[d03b.zip definitions directory zip file].

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.milyn.edi.unedifact</groupId>
    <artifactId>d03b-mapping</artifactId>
    <version>1.0.SNAPSHOT</version>
    <name>UN/EDIFACT - D03B - Mapping Model</name>

    <build>
        <plugins>
            <plugin>
                <groupId>org.milyn</groupId>
                <artifactId>maven-ect-plugin</artifactId>
                <version>1.4-SNAPSHOT</version>
                <configuration>
                    <src>d03b.zip</src>
                    <srcType>UNEDIFACT</srcType>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

Of course when we execute this step, we will perform "_mvn clean deploy_" and install the jar file in the http://smooks.org/mediawiki/index.php?title=Maven_%26_Ant[public maven repository], making it publicly available and thereby removing the need for you to perform this step.  A peek into the http://snapshots.repository.codehaus.org/org/milyn/edi/unedifact/[public SNAPSHOT repo] shows that we’ve started this process.

== Using a Mapping Model Set on the UN/EDIFACT Reader

Using a generated http://snapshots.repository.codehaus.org/org/milyn/edi/unedifact/[EDI Mapping Model set] jar in your application (via Smooks) is trivial.  You need to:

1. Add the generated http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] jar to your classpath (e.g. using a maven dependency configuration).
2. Add the _<unedifact:reader>_ configuration to your Smooks configuration, using the generated jar’s maven groupId, artifactId and version to reference that particular mapping model set through a URN (see below).

An example of the _<unedifact:reader>_ configuration for the above generated http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] jar for the http://www.unece.org/trade/untdid/down_index.htm[d03b.zip definitions directory zip] file would be as follows:

[source,xml]
----
<unedifact:reader
    mappingModel="urn:org.milyn.edi.unedifact:d03b-mapping:1.0-SNAPSHOT" />
----

Using the "_urn:<groupId>:<artifactId>:<version>_" URN pattern, Smooks can find the http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] jar file on the classpath,

And that’s about it.  The associated Smooks instance will accept a UN/EDIFACT message interchange containing one or more messages defined in the http://www.unece.org/trade/untdid/down_index.htm[d03b.zip definitions directory zip file], and will generate a stream of SAX events into Smooks, which can be processed using all the other Smooks capabilities (Java Binding, Validation, Templating etc).  As stated earlier, the improvements we are working on for EJC will result in us being able to generate Java Object models from an http://smooks.org/mediawiki/index.php?title=V1.4:Smooks_v1.4_User_Guide#Mapping_Model_Zip_Sets[EDI Mapping Model set] jar.

== Play with the Examples… and please give feedback

Check out and build the Smooks examples from https://svn.codehaus.org/milyn/trunk/smooks-examples (_mvn install_).

Change into the "ect-unedifact" directory after building all the examples (must build them all so as to install the poms) and run the example using mvn exec:java. The ect-unedifact example depends on the "d03b-mapping" module which has been pre-built and is available in the http://snapshots.repository.codehaus.org/org/milyn/edi/unedifact/[public SNAPSHOT repo].

And guys…. PLEASE let us know how you get on with this stuff… things you like and dislike etc !!!